### ISSUE TITLE
Error when email contains no real email

### ISSUE THREAD

**Issue by gerardo-navarro** [cmer/nobspw#1]
When creating a user record which contains a malformed email such as `gerardo` (without @ and host information), the password checker is not able to handle this case. Unfortunately, all validations in Rails are executed which is why the password checker get activated even though the email validation rejects the user record in Rails. The following error is raised:

```
     NoMethodError:
       undefined method `split' for nil:NilClass
     # /Users/gerardonavarrosuarez/.rvm/gems/ruby-2.4.1@foodstarter/gems/nobspw-0.3.0/lib/nobspw/validation_methods.rb:83:in `strip_extension_from_domain'
     # /Users/gerardonavarrosuarez/.rvm/gems/ruby-2.4.1@foodstarter/gems/nobspw-0.3.0/lib/nobspw/validation_methods.rb:79:in `email_without_extension'
     # /Users/gerardonavarrosuarez/.rvm/gems/ruby-2.4.1@foodstarter/gems/nobspw-0.3.0/lib/nobspw/validation_methods.rb:22:in `email_included_in_password?'
     # /Users/gerardonavarrosuarez/.rvm/gems/ruby-2.4.1@foodstarter/gems/nobspw-0.3.0/lib/nobspw/password_checker.rb:33:in `block in check_password'
     # /Users/gerardonavarrosuarez/.rvm/gems/ruby-2.4.1@foodstarter/gems/nobspw-0.3.0/lib/nobspw/password_checker.rb:32:in `each'
     # /Users/gerardonavarrosuarez/.rvm/gems/ruby-2.4.1@foodstarter/gems/nobspw-0.3.0/lib/nobspw/password_checker.rb:32:in `check_password'
     # /Users/gerardonavarrosuarez/.rvm/gems/ruby-2.4.1@foodstarter/gems/nobspw-0.3.0/lib/nobspw/password_checker.rb:22:in `weak_password_reasons'
     # /Users/gerardonavarrosuarez/.rvm/gems/ruby-2.4.1@foodstarter/gems/nobspw-0.3.0/lib/active_model/validations/password_validator.rb:20:in `validate_each'
     # ./spec/models/merchant_account_spec.rb:64:in `block (5 levels) in <top (required)>'
```

These helpers in `lib/nobspw/validation_methods.rb` should be more intelligent
```
def email_without_extension(email)
  name, domain, whatev = email.split("@", 3)
  "#{name}@#{strip_extension_from_domain(domain)}"
end

def strip_extension_from_domain(domain)
  domain.split(".").first
end
```

Maybe I can come up with a pull request in the near future

**Comment by cmer** [comment]
I'm quite late to the party... I just saw this. I just pushed a fix. I'll release soon. Sorry about that.
